apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-varver
  namespace: {{ .Values.namespace }}
data:
  varver.yaml: |
    secretName: {{ .Values.namespace }}/api
    envFileName: .env
    secretsMap:
      firebase.json: {{ .Values.namespace }}/firebase.json