apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      volumes:
      - name: varver
        configMap:
          name: {{ .Release.Name }}-varver
          items:
            - key: varver.yaml
              path: varver.yaml
      serviceAccountName: custom-s3-client
      containers:
      - name: {{ .Release.Name }}
        image: "000064010000.dkr.ecr.eu-central-1.amazonaws.com/{{ .Values.appName }}:{{ .Values.imageTag | default .Chart.AppVersion }}"
        imagePullPolicy: Always 
        command: ["/bin/bash"]
        args: ["migration.sh"]
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: varver
          mountPath: /app/varver.yaml
          subPath: varver.yaml
          readOnly: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cluster-services
                    operator: NotIn
                    values:
                      - "true"