namespace: "development"

domainName: dev.custom.com

replicaCount: 1

resources: 
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 100m
    memory: 252Mi

app:
  url: "https://ui.dev.custom.com/"
  env: dev
  trace_enabled: "true"
  throttling_limit: 5000
  login_token_expiration_time: "600"
  jwt_ignore_token_expiration: "false"
  